### PR TITLE
add support for rbac

### PR DESCRIPTION
**Pull request by usamaahmadkhan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Chart: logrotate Dry Run successful

**Comment by stakater-user** [comment]
@usamaahmadkhan Chart: logrotate Dry Run successful

**Comment by stakater-user** [comment]
@usamaahmadkhan Chart: logrotate Dry Run successful

**Comment by stakater-user** [comment]
@usamaahmadkhan Chart: logrotate Dry Run successful

**Review by kahootali — APPROVED** [review]

**Pull request merged**
